/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g859oFSV3DRmGwpuroRhgj

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantshejIcCe9LuEs } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hejICCe9luEs/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantshejIcCe9LuEs
});
